name: Metrics
on:
  # Se ejecuta a las 00:00 UTC cada día
  schedule: [{cron: "0 0 * * *"}]
  # Permite ejecutarlo manualmente desde la pestaña Actions
  workflow_dispatch:
  # Se ejecuta en cada push a la rama main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu token secreto
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Opciones de configuración
          user: felixbonillo
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Caracas
          
          # Plugin de lenguajes (Reemplaza al que te estaba fallando)
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 8
          plugin_languages_details: lines, percentage
